// Code generated by generate_code script - DO NOT EDIT.
package entity

import (
	"github.com/yuki-eto/remodel/example/entity"
	"go.knocknote.io/rapidash"
)

type Structable interface {
	Struct() *rapidash.Struct
}

func Structables() map[string]Structable {
	return map[string]Structable{"users": new(entity.User)}
}
func ReadOnlyStructables() map[string]Structable {
	return map[string]Structable{"units": new(entity.Unit)}
}
